### ISSUE TITLE
是否兼容vue3.0 ?

### ISSUE THREAD

**Issue by dalaohekele** [chenhengjie123/vue-testcase-minder-editor#4]
直接引入包报错
Uncaught TypeError: Cannot create property '__KityMethodClass' on boolean 'true'
    at extend (VueTestcaseMinderEditor.umd.min.js:29:15183)
    at Object.exports.createClass (VueTestcaseMinderEditor.umd.min.js:29:15798)
    at Object.value (VueTestcaseMinderEditor.umd.min.js:29:74314)
    at Object.r (VueTestcaseMinderEditor.umd.min.js:29:170)
    at Object.value (VueTestcaseMinderEditor.umd.min.js:29:28491)
    at Object.r (VueTestcaseMinderEditor.umd.min.js:29:170)
    at Object.value (VueTestcaseMinderEditor.umd.min.js:29:91052)
    at Object.r (VueTestcaseMinderEditor.umd.min.js:29:170)
    at Object.value (VueTestcaseMinderEditor.umd.min.js:29:17833)
    at Object.r (VueTestcaseMinderEditor.umd.min.js:29:170)

**Comment by flower-muxi** [comment]
我也是这个报错，请问解决了么？

**Comment by lrdong** [comment]
大佬 适配下Vue3吧，另外Element UI也不维护了
